#include "sm83.hpp"

// Unprefixed instructions
void SM83::ADC() {}
void SM83::ADD() {}
void SM83::AND() {}
void SM83::CALL() {}
void SM83::CCF() {}
void SM83::CP() {}
void SM83::CPL() {}
void SM83::DAA() {}
void SM83::DEC() {}
void SM83::DI() {}
void SM83::EI() {}
void SM83::HALT() {}
void SM83::INC() {}
void SM83::JP() {}
void SM83::JR() {}
void SM83::LD() {}
void SM83::LDH() {}
void SM83::NOP() {}
void SM83::OR() {}
void SM83::POP() {}
void SM83::PREF() {}
void SM83::PUSH() {}
void SM83::RET() {}
void SM83::RETI() {}
void SM83::RLA() {}
void SM83::RLCA() {}
void SM83::RRA() {}
void SM83::RRCA() {}
void SM83::RST() {}
void SM83::SBC() {}
void SM83::SCF() {}
void SM83::STOP() {}
void SM83::SUB() {}
void SM83::XOR() {}
void SM83::XXX() {}

// Prefixed instructions
void SM83::BIT() {}
void SM83::RES() {}
void SM83::RL() {}
void SM83::RLC() {}
void SM83::RR() {}
void SM83::RRC() {}
void SM83::SET() {}
void SM83::SLA() {}
void SM83::SRA() {}
void SM83::SRL() {}
void SM83::SWAP() {}
